/**
 * Wallet and CLOB Trading Types
 * Types for Polymarket CLOB remote signing and trading operations
 */

/**
 * Request body for the /sign endpoint
 * Frontend sends this to get builder signature headers
 */
export interface SigningRequest {
  method: string; // HTTP method: 'GET', 'POST', 'DELETE'
  path: string; // API path: '/order', '/orders', etc.
  body?: string; // JSON stringified request body (for POST/DELETE)
}

/**
 * Response from the /sign endpoint
 * Contains builder authentication headers to attach to CLOB requests
 */
export interface SigningResponse {
  POLY_BUILDER_API_KEY: string;
  POLY_BUILDER_SIGNATURE: string;
  POLY_BUILDER_TIMESTAMP: number;
  POLY_BUILDER_PASSPHRASE: string;
}

/**
 * Wallet connection information
 */
export interface WalletConnection {
  address: string;
  chainId: number;
  isConnected: boolean;
  provider?: 'metamask' | 'walletconnect' | 'coinbase' | 'privy';
}

/**
 * User's CLOB API credentials (L2 auth)
 * Generated by signing a message with the user's wallet
 */
export interface ClobApiCredentials {
  apiKey: string;
  secret: string;
  passphrase: string;
}

/**
 * Gnosis Safe proxy wallet information
 */
export interface ProxyWallet {
  address: string;
  isDeployed: boolean;
  owner: string; // User's EOA address
}

/**
 * Token approval status for trading
 */
export interface TokenApproval {
  tokenAddress: string;
  spenderAddress: string; // Exchange contract
  isApproved: boolean;
  allowance: string;
}

/**
 * Order validation result
 */
export interface OrderValidation {
  isValid: boolean;
  errors?: string[];
  warnings?: string[];
}

/**
 * User's trading profile
 */
export interface TradingProfile {
  address: string;
  proxyWallet?: string;
  totalVolume: string;
  totalTrades: number;
  openOrders: number;
  positions: number;
  pnl?: string;
}

/**
 * Gas estimate for transactions
 */
export interface GasEstimate {
  gasLimit: string;
  gasPrice: string;
  maxFeePerGas?: string;
  maxPriorityFeePerGas?: string;
}

/**
 * Token balance information
 */
export interface TokenBalance {
  tokenAddress: string;
  balance: string;
  decimals: number;
  symbol: string;
  formattedBalance: string;
}
